version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8080"
  sequence-upload-service:
    build: ./sequence-upload-service
    ports:
      - "8082:8080"
  analysis-service:
    build: ./analysis-service
    ports:
      - "8083:8080"
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: genoinsight
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6

